# ######################################################################################################################
# General server settings
# ######################################################################################################################
server.port=9001
logging.level.Exposed=DEBUG
application.domainName=${SERVER_DOMAIN}
springdoc.swagger-ui.path=/swagger-ui.html
#
# ######################################################################################################################
# Setting up the Database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.exposed.generate-ddl=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#
# ######################################################################################################################
# Custom security properties, used to create the user authentication cookies
system.security.enableEncryption=${SERVER_HTTPS}
system.security.password.resetLimitMinutes=15
system.security.jwt.path=/
system.security.jwt.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Xi9DAkO3ewysWYbrr0q9BidMtUjh7Hm81s2v2J1O3G3AkogCTuJhegj45yM37Qgalp5FZlY+8F+b7momRBvtq9Xz/eG3SUg7YaztEEqppyx/JFYeDHYUb1rgnW8Hyb8m520LjiNo+k4tTOCUr9Q09freBQIAw+e2DokuvuxmG8rJs72bjWisiCjkM1X9COLUtrjEpOBiFTPkj1tkOR/Cs+8GdLyeFMRBTzy+sslKknxrJMt/GmKYmR5JIxrERxluyIuUvMBFxGIWfp49/YNkHpnFVLy/CY1WcnvrBDFO1+F10oiRxaOn2uBb2EntQGx9eskQyiCi2R1FwTfDRN7ywIDAQAB
system.security.jwt.privateKey=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDdeL0MCQ7d7DKxZhuuvSr0GJ0y1SOHsebzWza/YnU7cbcCSiAJO4mF6CPjnIzftCBqWnkVmVj7wX5vuaiZEG+2r1fP94bdJSDthrO0QSqmnLH8kVh4MdhRvWuCdbwfJvybnbQuOI2j6Ti1M4JSv1DT1+t4FAgDD57YOiS6+7GYbysmzvZuNaKyIKOQzVf0I4tS2uMSk4GIVM+SPW2Q5H8Kz7wZ0vJ4UxEFPPL6yyUqSfGsky38aYpiZHkkjGsRHGW7Ii5S8wEXEYhZ+nj39g2QemcVUvL8JjVZye+sEMU7X4XXSiJHFo6fa4FvYSe1AbH16yRDKIKLZHUXBN8NE3vLAgMBAAECggEAVwzPha0Dxm/CBx9izx50hSgtlZ7YDcx7wfh+vt/0w04xiDlZeTeJGPSDMsJETuNugE8aW8aABshpqYF4ht1Cg7RM2CXrQP4IgMQa20Vn/cAGZ4c7llbFN2+0E72yGS6KSKJGgYpiBeS0EOjzlxGys+mhGHwLICTiIwxLhqFKj2abF0UJa5hY053E5HUuyYSfRjgmxp+J9FwJwWLFqvTMrshHdTVk/QnZynUpSE3VqZoTGtKQXBMjOmWLFLAneJzF9iPTwZQtafG6FKX/ORt1IYL/zq+lNUcpic+szZxX+2zyYDI2Z/6nYIWH9hAWfDHzmvelueugyp5WwyNqczlSSQKBgQDeQYHjPHAhnBSY7VFF+Cn3cs/QsEiamFicIo397dwn1dpsMVe+Oy4OZdPW0wz5gm9ysw98foQDltOVo70fiEmQi8qVY1ffQeAqMfQBBZ+6kUWvClUtm8wggsWXdyk4paJK7pkaxstvzF6mPasV8B8RJan88MsZ60iDnhtohdX0IwKBgQD/GL/O6Jb8H/lnEMNWuVdKdEaC8yqzspzUOGO45zAyKW93+T+PB2LYwCCRzXbTS/0Nue3M55QC6p/vZtbWI2NbR8MbzTIvo/pilwhpp5YMvrJRdItLmIxM5BVbf5AX1vBMhdTih4hhSJlID1mM5OV+CTZMnmH5H2ec7J/OWEFgOQKBgQDC1XQyqqm1nOilguzLRJgtdrVcwRx0gXa0MMp+vsRPG3Zlf//mIGTodDV3Tf5CwChIyVWbEiFSMCb9N9Ozz7qFfzYxLSw757jF5JJ9TtvOJkmK/6jZ2YjhOyJR/EDjirexrmYDBiASunqCiu7uxVfGpVjWBpRU/V/NGY33W9PKNwKBgQDvur1+3/wMQqwqHInGdXVAJhehto3ZxDA4DCpDORiE+4Wi1NzTOFi/Y4b4HoPdvFq6zJFa8AKb3wygeh/JrAYSYVVNSkAwn0SN5GvmhrSvk4KWpBTH3Tt0gyBDFZU/oiG/eEIBBOe4rPZHzw0UKIQ3NscNqAZgjQ/dXE4uJ6iAmQKBgQC65KypNCfXgkh5IW98KELryjT9jsYTC9/VfS/H4wzw88muaqjZ5yxoHkYvowVkNuWv+I7mZb6RCM1naUbnyydWckfiYbIWxT2pv6DfF/nYXTKkJRXxT7sLcuBhq3Hr62sL2qc6qpRjf3FS1tL/xfuv8lqBUkPkecsGF4EuBAId4Q==
system.security.jwt.expiration=86400
system.security.jwt.cookieName=USERSESSION
system.security.jwt.issuer=LinceTech
system.security.jwt.secureCookie=${JWT_SECURE_COOKIE}
system.security.jwt.sameSite=None
#
# ######################################################################################################################
# Custom e-mail settings, used to create the user authentication cookies
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT_A}
spring.mail.email=${SMTP_EMAIL}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.port=${SMTP_PORT_B}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
#
# ######################################################################################################################
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:baeldung.p12
server.ssl.key-store-password=123456789
server.ssl.key-alias=baeldung
server.ssl.enabled=false

spring.security.oauth2.client.registration.google.client-id: 464253389303-hil70um9lpkedrh190b8ctv370tjb964.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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