server.port=9001

# ######################################################################################################################
# Setting up the Database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.exposed.generate-ddl=true
spring.datasource.username=postgres
spring.datasource.password=root